Feature/redesign latest experiment cards
ebi-gene-expression-group/atlas-latest-experiments-panel pull request #1
Opened 2018-12-05 10:40 UTC by lingyun1010

Thanks for your comments. I have made commits for the HTML tag style. As for `aria-` attributes in `<span>`, those are from the original latest experiment tab CSS from the current SC homepage.

2018-12-05 10:45 UTC, alfonsomunozpomer reviewed
Just a couple of questions. Address changes if needed. Feel free to discuss this and I’ll approve everything is clear.

2018-12-05 10:45 UTC, alfonsomunozpomer commented on src/containers/SceaHomePageLatestExperimentContainer.js
> +  host: PropTypes.string
Is `host` required or is it optional?

2018-12-05 10:45 UTC, alfonsomunozpomer commented on src/cards/LatestExperimentCard.js
> +        <span className={`button secondary no-action fixed-width-medium has-tip`} data-tooltip={`fmjj2g-tooltip`} title={``}
What are these `data` and `aria` attributes for? If `title` is empty, just remove it.

2018-12-05 12:04 UTC, lingyun1010 commented on src/containers/SceaHomePageLatestExperimentContainer.js
> +  host: PropTypes.string
It is required to redirect page by clicking `See all species` buttons. I will add `isRequired` for this prop.

2019-02-26 23:59 UTC, alfonsomunozpomer commented on src/containers/SceaHomePageLatestExperimentContainer.js
> +  cards: PropTypes.arrayOf(PropTypes.shape(latestExperimentCardPropTypes)).isRequired,
As a rule of thumb, try to have each component’s prop types in the same file as the component itself. In the cases where we have a separate file it’s because the prop types are shared among multiple components without a clear hierarchy. Here, you could just as well have `LatestExperimentCard.propTypes` and get rid off the aditional file.

2019-02-27 00:25 UTC, alfonsomunozpomer requested changes
Since this is a new repo some of the comments here refer to files which don’t specifically belong in this PR.

Using the term “card” here is a bit of a stretch. We call *cards* the components which match the JSON schema as defined in [Atlas Homepage Cards](https://github.com/ebi-gene-expression-group/atlas-homepage-cards), so let’s look for a more suitable name to avoid confusion. I think this component could be called, for instance, Atlas Latest Experiments Panel. Please rename the repo and the package name as required. If you have any other ideas about the component name we can discuss it in our daily stand-up to get feedback from the whole team.

Instead of relying on styles defined in `atlas.css` (`fixed-width-medium`, `no-action`, `clear`, etc.) use CSS-in-JS. I could see that you’re using plain style objects in `renderContentListItems.js`. Consider using [styled components](https://www.styled-components.com/) (otherwise, remove the dependency altogether).

What’s the purpose of `renderContentListItems.js`? Is it used anywhere at all?

What are all the exports in `html/render.js` about? I think you left them from previous edits.

I can see some wild double quotes around. ;)

In principle the core functionality is there. Besides the nitpicking above, we should try to make this a general latest experiments panel that could cover both bulk and SC. Once the above is done let me know and we can discuss how to make it work for both projects.

2019-02-27 00:25 UTC, alfonsomunozpomer commented on src/containers/SceaHomePageLatestExperimentContainer.js
> +  cards: PropTypes.arrayOf(PropTypes.shape(latestExperimentCardPropTypes)).isRequired,
As a rule of thumb, try to have each component’s prop types in the same file as the component itself. In the cases where we have a separate file it’s because the prop types are shared among multiple components without a clear hierarchy. Here, you could just as well have `LatestExperimentCard.propTypes` and get rid off the aditional file.

2019-02-28 10:09 UTC, alfonsomunozpomer requested changes
I think this is definitely an improvement. Just two details: could you change the indentation in `render.js` and `SceaHomePageLatestExperimentPanel.js` to use consistently two spaces? Remember also to add the Travis and Coveralls badges in the README file.

2019-02-28 10:09 UTC, alfonsomunozpomer commented on src/SceaHomePageLatestExperimentPanel.js
> +const LatestExperimentPanel = ({numberOfAssays, host, experimentAccession, lastUpdate, experimentDescription, species}) =>
I think a better name would be `LatestExperimentEntry`. Notice that the panel itself is the outside `<div>`.

2019-02-28 15:38 UTC, alfonsomunozpomer approved these changes

2019-02-28 15:38 UTC, merged